load(
    "@d2l_rules_csharp//csharp:defs.bzl",
    "csharp_binary",
)

csharp_binary(
    name = "hello",
    srcs = ["hello.cs"],
    target_frameworks = [
        "net46",
        "net47",
        "net472",
    ],
)
