name: "Build"
on:
  pull_request:
  push:
    branches: master
    paths:
    - examples/*
    - examples/*/*
    - examples/*/*/*
    - examples/*/*/*/*
    - examples/*/*/*/*/*
    - BUILD
    - WORKSPACE
    - .github/workflows/usage.yml
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://gcr.io/bazel-public/ubuntu1804:java11
        with:
          args: "bazel build //..."