name: "Build"
on:
  push:
    paths:
    - examples/*
    - examples/*/*
    - examples/*/*/*
    - examples/*/*/*/*
    - examples/*/*/*/*/*
    - BUILD
    - WORKSPACE
    - .github/workflows/main.yml
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Bazel
        uses: abhinavsingh/setup-bazel@v3
      - name: Bazel Build
        run: bazel build //...