name: "Build"
on:
  pull_request:
  push:
    branches: master
    paths:
    - examples/*
    - examples/*/*
    - examples/*/*/*
    - examples/*/*/*/*
    - examples/*/*/*/*/*
    - BUILD
    - WORKSPACE
    - .github/workflows/main.yml
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker://gcr.io/cloud-marketplace-containers/google/bazel
        with:
          args: "build //..."
